services:
  chemediaho:
    image: gablilli/chemediaho:latest
    container_name: chemediaho
    ports:
      - "8001:8001"
    environment:
      FLASK_ENV: production
      # HTTPS_ENABLED: "true"
    volumes:
      # persiste la secret key fuori dal container
      - ./secret_key.txt:/app/secret_key.txt
    restart: always
